### ISSUE TITLE
Mash - memory issue - memory issue climbed very high and run out of memory

### ISSUE THREAD

**Issue by dam04** [marbl/Mash#101]
Hi Mash Developer

I am helping an user to run "mash sketch" genome comparisons for 8000 sequences, but every time after 20-30 minutes, it is hit with OOM-kill event(Out of memory), we suspected that there is memory leak somewhere.

We tried with both source compiled and pre-compiled Linux binaries version mash 2.1 

Compiled with gcc/4.9.3 :

./bootstrap.sh

./configure --prefix=/usr/local/mash.2.1 --with-capnp=/usr/local/capnproto --with-gsl=/usr/local/gsl/2.2-gcc4 --with-boost=/usr/local/boost/1.62.0-gcc4

make

sudo make install 

I hope that you can provide us with some insights on this issue.

Kindly advise.

Many Thanks

Damien

**Comment by marlam89** [comment]
Hi MASH developer,

Just jumping in to say that we've been trying to get this to run on CentOS Linux release 7.3.1611 if this information helps with sorting the above issue. Thank you in advance for your time and assistance. 

Kindest,
Margaret

**Comment by dam04** [comment]
#
[config.log](https://github.com/marbl/Mash/files/2537234/config.log)

This is config.log of the above make

**Comment by dam04** [comment]
The user is using genomes from RefSeq assigned to the Klebsiella genus, so most should be around 5.5-6.5 Mbp in size.

mash sketch -s 100000 -p 8 -o kleborate_data_sketchfile -i /projects/js66/data/klebsiella/pneumoniae/alfred2/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/alice_springs/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/bialek2014/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/bowers2015/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/chung2015/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/davis2015/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/deleo2014/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/ellington2016/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/global/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/Henson2017/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/singapore_pla2015/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/smit_2017/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/stoesser2013/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/stoesser2014/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/struve2015/assemblies/*.fasta /projects/js66/data/klebsiella/pneumoniae/wand2015/assemblies/*.fasta /projects/js66/individuals/margaret/refseq_170918/bacteria/*/*.fna.gz

mash dist -p 8 kleborate_data_sketchfile.msh kleborate_data_sketchfile.msh > distances


I hope that this is helpful.

Damien

**Comment by marlam89** [comment]
Hi Brian,

Thank you so much for pointing this out, this is indeed not what we intended and I will remove the -i flag in future. Thank you again. 

Kindest,
Margaret
