### ISSUE TITLE
mash triangle -l fofn.txt sketching seqs not files

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#120]
If I use the `-l fofn.txt` (file of filenames) to `mash triangle`, the matrix has one line per SEQUENCE instead of one line per file (each file is a multifasta).  It's like `-i` is automatically on, and there is no option to disable `-i` (sketch each sequence).

**Comment by ondovb** [comment]
Thanks, should be fixed in tip.

**Comment by tseemann** [comment]
Can you `git tag v2.2.1 && git push --tags` please? :)

**Comment by tseemann** [comment]
Pretty please?

It seems broken for *.fasta too, not just -l fofn

**Comment by ondovb** [comment]
Done!

**Comment by ondovb** [comment]
I'm not seeing (2). Except if the wildcard resolves to a single file, in which case it assumes -i because otherwise there would be nothing to compare.

**Comment by tseemann** [comment]
You are correct about (2) - not sure what I did wrong.  It's good to go now!
