### ISSUE TITLE
Mash distance threshold for bacterial genus?

### ISSUE THREAD

**Issue by zifanzhu** [marbl/Mash#121]
Hi there,

In the Mash paper, Mash distance <= 0.05 roughly corresponds to the definition of bacterial species. Is there any suggested Mash distance threshold for bacterial genus?

Best,
Zifan

**Comment by tseemann** [comment]
I don't think there is any corresponding threshold for bacterial genera, but maybe @dparks1134 knows.

**Comment by dparks1134** [comment]
Hi Zifan. ANI is generally not recommended for circumscribing genera. MASH is also a poor approximation of BLAST-based ANI values for such divergent species. AAI is more commonly used for circumscribing genera. A nice implementation of this is MiGA:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6031002/

That said, the following preprint does explore using ANI to circumscribe species:
https://www.biorxiv.org/content/10.1101/392480v1
