### ISSUE TITLE
mash 2.2.1 release reports itself as 2.2 still 

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#124]
This commit to update the printed version
https://github.com/marbl/Mash/commit/c8f5f96934367d98a408a40a1dc270c04c9c0987
was made _after_ the release here:
https://github.com/marbl/Mash/releases/tag/v2.2.1

Can you please increment code to 2.2.2 and release 2.2.2 please?

**Comment by ondovb** [comment]
Sure! Just want to double check that #120 is resolved?

**Comment by tseemann** [comment]
#120 is resolved, not patches needed. Thank you!

**Comment by ondovb** [comment]
Ok, made performance improvement from #118 and tagged v2.2.2.
