### ISSUE TITLE
seed match warning – recent install (2.2)

### ISSUE THREAD

**Issue by goertzenlr** [marbl/Mash#127]
As per #62 and #74 

$mash dist RefSeq88n.msh test1.msh > testdist1.tab

WARNING: The sketch test1.msh has a seed size (42) that does not match the current seed (0). This file will be skipped. 

However in this case newly installed v2.2 binaries, so a re-download does not seem to be the solution. 

Thanks

**Comment by ondovb** [comment]
The RefSeq88 sketches that were released with the screen paper do have a seed of 0, so this can be fixed by adding `-S 0` when creating `test1.msh`. We will likely make this the default in upcoming versions, but for now the seed argument will be needed to use the RefSeq88 sketches.
