### ISSUE TITLE
Which release or date of refseq.genomes.k21.s1000.msh

### ISSUE THREAD

**Issue by ssun6** [marbl/Mash#139]
Hi, 

Could you let me know which release of Refseq is the refseq.genomes.k21.s1000.msh based on? Thank you!

**Comment by ondovb** [comment]
It's release 93

**Comment by ssun6** [comment]
Thank you!

**Comment by nsarode-joyn** [comment]
I keep having this question often. Is there a way where I can check the release number somewhere without bugging someone here ? Or even better, could the release number be integrated within the filename when we download it from https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh ?
