### ISSUE TITLE
ERROR reading file?

### ISSUE THREAD

**Issue by thh32** [marbl/Mash#143]
Hi,

I have been running MASH as part of a larger python script using the command;

```
bashCommand = '/home/ecoli/Programs/mash-Linux64-v2.2/mash dist bin/MAG_database/MAG_MASH_all.msh ' + genome_file + ' -t > Output/' + project_name + '/MAG_MASH.txt'
print bashCommand
process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
```

Everytime I run this I get the following error;

```
/home/ecoli/Programs/mash-Linux64-v2.2/mash dist bin/MAG_database/MAG_MASH_all.msh /DATA/Hitch_analysis/Protologger/v0.3-Poyet/Input/GCA_008415625.1_ASM841562v1_genomic/GCA_008415625.1_ASM841562v1_genomic.fna -t > Output/DATA/MAG_MASH.txt
ERROR: could not open > for reading.
```

The only time i dont get this is if I remove the `-t >Output...` section and then it runs without giving errors. Additionally if I run the `bashCommand` in the command line it runs without issue.

Any idea what is causing this error or what I could do to resolve it?

**Comment by ms-gx** [comment]
I think this is not a problem with Mash. Try to provide `shell=True` in the `subprocess.Popen` call.

Your problem is probably described here:
https://stackoverflow.com/questions/21135694/using-greater-than-operator-with-subprocess-call

**Comment by thh32** [comment]
Thank you so much for the suggestion, it now works perfectly!
