### ISSUE TITLE
Conda Install: Still Version 1.1

### ISSUE THREAD

**Issue by womandrea** [marbl/Mash#144]
I'm trying to install mash through conda, which claims it should be on version 2.2.2, however, when I have install it, the package seems to be resulting in me having mash 1.1

I'm not certain if this is an issue with conda or something I'm doing. I see in the files that version 2.2.2 is available, I'm not certain as to why that's not the one being downloaded. 

The command I run is: 
`conda install -c bioconda mash`

which is what it says to do on conda. 

Anything helps, sorry because I know this is super mundane!

**Comment by roblanf** [comment]
@womandrea how did you solve this? Having the same issue here and can't figure out what I'm doing wrong.

**Comment by womandrea** [comment]
I'm not sure what was causing it, but forcing the version in the command was the fix for me. 

`conda install mash=2.2.2` or `conda install -c bioconda mash=2.2.2` should do the trick!

Hopefully that works for you!
