### ISSUE TITLE
mash triangle matrix

### ISSUE THREAD

**Issue by susheelbhanu** [marbl/Mash#145]
Hey all, 

I managed to generate a matrix using **mash triangle**. 

I now have a very naive question about it though and wanted to confirm something - the diagonals - are they zeros (0)s?

Thank you!
[triangle_matrix.txt](https://github.com/marbl/Mash/files/4586939/triangle_matrix.txt)

**Comment by kloetzl** [comment]
The main diagonal has to be zero because a sequence has zero substitutions when compared to itself.

**Comment by susheelbhanu** [comment]
Thank you @kloetzl
