### ISSUE TITLE
Question - saving ref sketches and different versions of MASH

### ISSUE THREAD

**Issue by CarmenSheppard** [marbl/Mash#156]
Sorry if this has been asked before / couldn't see it in docs. If i'm using screen against refs that I've saved the sketches for reuse in a program I'm writing. Should I resketch the refs if a different version of Mash is used? I noticed changes to the sketching in version 2.3, I have refs sketched using 2.2. - should I redo the sketches or would the originals be fine?
Also the other way if I sketched with version 2.3 for the refs but then someone used version 2.2 or lower for screen could that potentially cause issues?

**Comment by ondovb** [comment]
The sketches are compatible across versions. The one exception is that if the seed was changed from the default (`-S` in 2.x), the sketches will not work with 1.x operations.

**Comment by CarmenSheppard** [comment]
Brilliant, thanks. I had actually been using like that (with older sketches) but good to know it's not going to cause a problem.
