### ISSUE TITLE
Parallelism for mash dist

### ISSUE THREAD

**Issue by kaganr** [marbl/Mash#23]
The '-p' option for "mash dist"  does not appear to be working.  Only one core is used even if I set -p to an integer greater than 1.  OS: Redhat 6 Linux server; mash version 1.0.2 (downloaded executable for 64-bit linux).

Example:
mash dist -d 0.05 -p 8 database.msh query_seqs.msh > distances.tab

**Comment by ondovb** [comment]
Currently, to take advantage of parallelism, the query must be split into multiple sketch or fasta files and provided as multiple queries on the command line. This is something that should be improved in the future (related to issue #6).

**Comment by ondovb** [comment]
Fixed in [v1.1](https://github.com/marbl/Mash/releases/tag/v1.1). Threads will now take chunks of comparisons (currently 4096) at a time to avoid overhead, but do not need separate files.
