### ISSUE TITLE
Cannot download refseq.msh

### ISSUE THREAD

**Issue by daveuu** [marbl/Mash#24]
The link in the docs to the pre-sketched RefSeq archive `https://github.com/marbl/Mash/raw/master/data/refseq.msh` returns only the LFS info:
```
version https://git-lfs.github.com/spec/v1
oid sha256:3292c28efedf8a2144494b99bdb784d94b1d737d6f942f29a17daf73b7d61d3e
size 97678488
```
I expected to click on the link and be prompted to download a 97MB file. Perhaps something to do with an exceeded quota? I went the long way round and installed the git lfs extension to fetch from within a cloned Mash repo, but this also fails with:
```
$ git lfs fetch
Fetching master
Git LFS: (0 of 4 files) 0 B / 107.44 MB                                                  
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
```

**Comment by skoren** [comment]
Yes, this is github imposing a quota on the allowed downloads of a file. The file is hosted here:
http://gembox.cbcb.umd.edu/mash/RefSeqSketches.msh.gz 
(from the supporting data docs page). I'll update the other docs to point to this file as well.

**Comment by ondovb** [comment]
I got the one in the tutorial.

**Comment by daveuu** [comment]
Thanks!
