### ISSUE TITLE
Can you make a 1.03 release?

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#25]
There's been lots of bugfixes etc since 1.02 - any chance of an official 1.03 release?

Would help us package maintainers.

**Comment by ondovb** [comment]
There were some significant overhauls that we are saving for a 1.1 once we are convinced they are stable. In the meantime any feedback/testing on the latest source is appreciated. In particular I have seen a "file has no sequences" bug when doing highly parallel sketching that I would like to track down before a new release.

**Comment by ondovb** [comment]
Released [v1.1](https://github.com/marbl/Mash/releases/tag/v1.1)
