### ISSUE TITLE
mash dist -i throws std::bad_alloc on pac bio data

### ISSUE THREAD

**Issue by lynxoid** [marbl/Mash#28]
Hi,

I ran Mash v1.0.1 on a sample PacBio data against the refseq.msh database:

```
mash dist -i refseq.msh BEI_staggered_2kb.fastq  > BEI_staggered_2kb_dashI_1.1.mash
```

and got the following error after 48s:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

(also saw this in v1.0)

**Comment by ondovb** [comment]
The crash itself is fixed in v1.1, though I doubt sketching individual PacBio reads (via `-i`) will yield meaningful results against the full genomes in RefSeq. The new `-r` flag would be more appropriate, assuming you are trying to find the nearest reference to a sequenced isolate.
