### ISSUE TITLE
Static build plus binary as mentioned in INSTALL.txt

### ISSUE THREAD

**Issue by aslett1** [marbl/Mash#3]
Hi,

Two issues in one.

a) INSTALL.txt mentions that distribution is normally as a binary for Linux but there's no link to the binary and it's not mentioned on http://mash.readthedocs.org/en/latest/ - is this because the software is pre-publication or is there a link I'm missing?

b) I'm compiling using GCC4.8 on a system on which the standard GCC is 4.6 so trying to do so statically (Makefile contains "CPPFLAGS += -static-libstdc++ -L/software/gcc-4.8.1/lib64/"). Not sure whether the problem is that libstdc++.a at our end is dynamically built or whether something is amiss above (the path to gcc-4.8.1 is correct)? We're working round this using a bash script to set LD_LIBRARY_PATH and run mash.

Thanks,

Martin

**Comment by aphillippy** [comment]
Hi Martin,
a) We have not yet cut a first release of Mash yet. That should come in a few weeks, along with a static build, which may also solve problem (b).
b) Setting LD_LIBRARY_PATH is probably the easiest solution for now.

I hope you find the software helpful!

Best,
-Adam
