### ISSUE TITLE
Problems compiling with capnp

### ISSUE THREAD

**Issue by mw55309** [marbl/Mash#31]
Hi

I have a local installation of capnp which I specifiy in the configure step:

./configure --prefix=/exports/cmvm/datastore/eb/groups/watson_grp/software/Mash --with-capnp=/exports/cmvm/datastore/eb/groups/watson_grp/software/capnproto/

But when I "make" I get an error:

/exports/cmvm/datastore/eb/groups/watson_grp/software/capnproto//bin/capnp compile -oc++ MinHash.capnp
c++: no such plugin (executable should be 'capnpc-c++')
c++: plugin failed: exit code 1

The executeable it refers to does actually exist in capnproto/bin/capnpc-c++

I'm using Cap'n Proto version 0.5.3

Cheers
Mick

**Comment by ondovb** [comment]
Looks like Capnp's bin/ has to be in $PATH to find its helper programs. I updated the Makefile to do this automatically.

**Comment by ondovb** [comment]
You may have also run into this error:
https://github.com/Homebrew/homebrew-science/issues/3410
...which should be fixed now. I will close this for now; feel free to reopen if you are still seeing a problem.

**Comment by shaman-narayanasamy** [comment]
Hi,

I am facing this issue at the moment. I tried to do a normal configure with the `--perfix=$HOME`, but it did not find capnp, which should not be an issue because it is located in:
```
$ which capnp
/home/users/snarayanasamy/bin/capnp
```
Therefore, I amended the command to tell the configure exactly where it is located:
```
$ ./configure --prefix=$HOME --with-capnp=/home/users/snarayanasamy/bin/capnp
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for capnp... no
configure: error: Cap'n Proto compiler (capnp) not found.
```

As you can see, it still does not find. Is there something I am doing wrong?

Best regards,
Shaman

**Comment by ondovb** [comment]
Try without `bin/capnp`

**Comment by shaman-narayanasamy** [comment]
Thanks, that work for both the capnp and gsl. I though they were supposed to find it themselves because the prefix was provided. In any case, I reached another error:
```
cd src/mash/capnp;export PATH=/home/users/snarayanasamy/bin/:/work/projects/ecosystem_biology/local_tools/454_data_analysis_tools/install/bin:/XF/v2.3/App/Scripts:/XF/v2.3/specific/bin:/XF/v2.3/specific/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/lmod/lmod/libexec:/usr/local/sbin:/usr/sbin:/sbin:/home/users/snarayanasamy/bin:.:/home/users/snarayanasamy/.rvm/bin:/XF/v2.3/Admin/Scripts:/home/users/snarayanasamy/bin:/home/users/snarayanasamy/sandbox:/mnt/nfs/projects/ecosystem_biology/local_tools/sortmerna-1.99-beta:/home/users/snarayanasamy/bin/tbl2asn:/home/users/snarayanasamy/lib:/mnt/nfs/projects/ecosystem_biology/local_tools:/home/users/snarayanasamy/consed/genome/bin:/mnt/nfs/projects/ecosystem_biology/local_tools/abyss-1.5.2/ABYSS:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/cuda/bin:/home/users/snarayanasamy/bin:/home/users/snarayanasamy/sandbox:/home/users/snarayanasamy/bin/tbl2asn:/home/users/snarayanasamy/lib:/mnt/nfs/projects/ecosystem_biology/local_tools:/home/users/snarayanasamy/consed/genome/bin:/mnt/nfs/projects/ecosystem_biology/local_tools/idba-1.1.1.icc/bin:/mnt/nfs/projects/ecosystem_biology/local_tools/idba_mtp/idba_mt:/mnt/nfs/projects/ecosystem_biology/local_tools/idba_mtp/idba_mtp:/mnt/nfs/projects/ecosystem_biology/local_tools/sortmerna-1.99-beta:/mnt/nfs/projects/ecosystem_biology/local_tools/trinityrnaseq_r20140717:/mnt/nfs/projects/ecosystem_biology/local_tools/QIIME/build:/mnt/nfs/projects/ecosystem_biology/local_tools/DRISEE:/mnt/nfs/projects/ecosystem_biology/local_tools/Platypus_0.7.9.1:/mnt/nfs/projects/ecosystem_biology/local_tools/gkno_launcher/tools/freebayes/bin:/mnt/nfs/projects/ecosystem_biology/local_tools:/mnt/nfs/projects/ecosystem_biology/local_tools/picard/picard-tools-1.85:/mnt/nfs/projects/ecosystem_biology/local_tools/Platypus_0.7.9.1:/mnt/nfs/projects/ecosystem_biology/local_tools/vcftools/bin:/mnt/nfs/projects/ecosystem_biology/local_tools/htqc-1.91.1/bin:/mnt/nfs/projects/ecosystem_biology/local_tools/tabix-0.2.6:/mnt/nfs/projects/ecosystem_biology/local_tools/sratoolkit/linux/gcc/stat/x86_64/rel/bin:/home/users/snarayanasamy/metaCRT:/mnt/nfs/projects/ecosystem_biology/local_tools/htslib/htslib-1.2.1:/mnt/nfs/projects/ecosystem_biology/local_tools/bhsne_binning/bh_tsne;capnp compile -I /home/users/snarayanasamy/include -oc++ MinHash.capnp
capnp: symbol lookup error: /home/users/snarayanasamy/lib/libcapnp-0.5.3.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm
make: *** [src/mash/capnp/MinHash.capnp.h] Error 127
```

Best regards,
Shaman

**Comment by ondovb** [comment]
In this case `--prefix` is just where to put install targets. The new error I have not seen. What is your GCC version, and do you happen to have a custom GCC version in your home directory also?

**Comment by shaman-narayanasamy** [comment]
Alright. I misunderstood the `--prefix`. Also, the default compiler on our computing cluster is outdated. I had to manually load the latest one. Sorry, my bad! Everything works now :)

Thanks very much for the support!

**Comment by ondovb** [comment]
No problem, glad it was resolved.

**Comment by Lcornet** [comment]
Hello,

I have the same issue with capnp:

./configure --prefix=/usr/local --with-capnp=/usr

checking for capnp... yes
checking capnp/common.h usability... no
checking capnp/common.h presence... no
checking for capnp/common.h... no
configure: error: Cap'n Proto headers not found.


I installed capnpproto on centos7 with yum,
which capnp
/bin/capnp

 could you help me to fix that ?

Thanks,
Luc

**Comment by APrabhu21** [comment]
Hey @Lcornet did you end up figuring out how to solve that issue, I'm currently facing the same issue.

Thanks,
Atharva
