### ISSUE TITLE
Sketching paired-end read data

### ISSUE THREAD

**Issue by mw55309** [marbl/Mash#32]
Hi 

I note no mention of paired-end data in the docs; sketching with multiple files creates a multi-file sketch, but if I want a single sketch per paired-end sample, how is this done?

I assume I should be able to use sub-shells and/or zcat and pipe to stdin; however when i did this on our cluster I got core dumps (admittedly I seem to be having some problems with zcat on our cluster....)

At the very least it may be a good idea to update your docs to reflect how to sketch paired-end read data

Cheers
Mick

**Comment by ondovb** [comment]
You have the right idea catting to stdin. I added this step to the tutorial to clarify, but this could certainly be more elegant, maybe with a flag that pools all inputs into one sketch (possibly a behavior of the read flag `-r`).

If you want to try avoiding `zcat`, you can cat the gz files directly; `mash` will deflate each one in-stream.

**Comment by mw55309** [comment]
I do seem to have this persistent core dump:

zcat SRR1262647_1.fastq.gz | ../mash-Linux64-v1.1/mash sketch -k 21 -r -
Sketching from stdin...
Segmentation fault

Same with cat:

cat SRR1262647_1.fastq.gz | ../mash-Linux64-v1.1/mash sketch -k 21 -r -
Sketching from stdin...
Segmentation fault

Works fine without piping:

 ../mash-Linux64-v1.1/mash sketch -k 21 -r SRR1262647_1.fastq.gz
Sketching SRR1262647_1.fastq.gz...

Any ideas?

**Comment by ondovb** [comment]
Looks look stdin input was broken in 1.1. A fix is now in the latest source and will be included in the next release.

**Comment by ondovb** [comment]
Should be fixed in [v1.1.1](https://github.com/marbl/Mash/releases/tag/v1.1.1).

**Comment by alienzj** [comment]
Hello,
```
cat sample_1.fq.gz sample_2.fq.gz | mash sketch -k 21 -s 10000 -r - -o sample
mash info sample.msh
```
output:
```
Header:
  Hash function (seed):          MurmurHash3_x64_128 (42)
  K-mer size:                    21 (64-bit hashes)
  Alphabet:                      ACGT (canonical)
  Target min-hashes per sketch:  10000
  Sketches:                      1

Sketches:
  [Hashes]  [Length]   [ID]  [Comment]

  10000     815194870  -      -
```
The ID is empty.
If we have many samples pair-ended fastq files, and get sketch for each sample, then paste all into a single file, then mash dist it, finally all ID is empty.

We can do bellow:
```
cat sample_1.fq.gz sample_2.fq.gz > sample.fq.gz
mash sketch -k 21 -s 10000 sample.fq.gz -o sample
```
so can avoid ID issue, but couldn't enjoy the pleasure of unix stream pipeline : )

Thanks for the author
Such a great and creative tool！

**Comment by ondovb** [comment]
In latest source the `-r` flag will combine all input files and allows filling the empty fields with `-I` and `-C`.

**Comment by mw55309** [comment]
Hi, which version of mash is the -I and -C parameters implemented in?

I just installed 2.3 (using conda) and they're not there.....

Cheers
Mick
