### ISSUE TITLE
RefSeq database mash question

### ISSUE THREAD

**Issue by bioinfonm** [marbl/Mash#34]
Hello,

  I discovered Mash through the khmer website and author. I had a question about the the RefSeq database .msh file was built. Was each genome run with mash sketch and then compiled together to form the database? I'd like the extend the database and want to make sure I follow best practices for this.

Thanks,
ara

**Comment by ondovb** [comment]
Yes, although each `mash sketch

**Comment by ondovb** [comment]
Yes, although we gave each `mash sketch` command a batch of genomes for efficiency. To combine you would do something like:

`mash paste combined refseq.msh new.msh`

Also make sure to use the same sketching parameters as the original when making the new sketch, which would be `-s 400 -k 16` for our RefSeq sketch.

**Comment by bioinfonm** [comment]
@ondovb Thanks for the clarification.

**Comment by sheikki** [comment]
Perhaps something like below, assuming that all the files end in .fna and are located in cwd, and that GNU parallel is in $PATH:

```
#!/bin/bash
function mashSketch() {
    mash sketch -o $(basename "$1" .fna).msh
}

export -f mashSketch
find . -maxdepth 1 -type f -name "*.fna" | parallel -j 16 mashSketch {}
mash paste mydb.msh -l $(find . -maxdepth 1 -type f -name "*.msh")
```
