### ISSUE TITLE
Getting hashes out of .msh

### ISSUE THREAD

**Issue by bioinfonm** [marbl/Mash#35]
Hello,

  I was following the issues on: https://github.com/marbl/Mash/issues/27 .
I was wondering if there is a way to get the hashes from the .msh files. I am bouncing around between Mash and sourmash.

Thanks,
ara

**Comment by ondovb** [comment]
It's not in a release yet, but if you build from the latest source, you can do `mash info -d` to dump in JSON format with the hashes as plain text integers.

**Comment by bioinfonm** [comment]
Thanks!
