### ISSUE TITLE
Compare to refseq70 output - what are the columns? 

### ISSUE THREAD

**Issue by bioinfonm** [marbl/Mash#36]
Hello,

 When I compare my file to the refseq70.msh file and the do the sort | head I see several columns. 
refseq-NC-562-PRJNA178640-.-.-pColK_K235-Escherichia_coli.fna	A1.10.1000.fast0.23011	2.52707e-27	4/1000

The first column is what it is hitting to the in the refseq70
The second column is my file
The third column is: ? (I am guessing some percent)
The fourth is the p-value
The fifth, is that the number of hashes that match? 

Thanks!
ara

**Comment by ondovb** [comment]
Correct; the third column is the "Mash distance" that is derived in the paper.

This may help you further:
http://mash.readthedocs.io/en/latest/tutorials.html
