### ISSUE TITLE
Mash workflow from sequence to hash question

### ISSUE THREAD

**Issue by bioinfonm** [marbl/Mash#37]
Hello,

  I was reading through the Mash paper (Fig. 1) and the documents to try and understand the whole workflow.

**1)** kmers are calculated for each sequence in a file .
So for k=31 I get a bunch of kmers for each sequence. Are all the kmers for a single sequence hased or is there some pooling/cluster of all like kmers before being hashed? 

**2)** End up with a file of hased kmers.

**3)**The hashed kmers for two sets can be compared. 
For comparing two hased kmers in different sets is the Poisson model of mutations used to find similar kmers? Or is this used in 1 to find similar kmers within a file?

Thanks for helping with my understanding here.

ara

**Comment by ondovb** [comment]
I'm not sure if this is exactly what you're asking, but k-mers are treatly distinctly, e.g. two instances of ACGT will only be represented by one hash in the sketch. The Poisson model is not used for finding k-mers, but rather for translating the number of shared (exactly matching) k-mers into an estimate of nucleotide identity, based on how you would expect mutations to affect k-mer content (this is derived in the Fan et al. paper referenced in the Mash paper).
