### ISSUE TITLE
Compare to refseq70 - Column with matched hashes

### ISSUE THREAD

**Issue by bioinfonm** [marbl/Mash#39]
Hello,

  I was wondering if it's possible to get which hashes match to a given refseq hash. I know the output gives you number of hashes hit. I was hoping to know which hashes those were. 

Thanks!
ara

**Comment by ondovb** [comment]
Not directly, although now that the hashes for a particular sketch can be dumped in JSON format via `mash info -d`, it would be fairly straightforward to compare which ones actually match. Just note that only the first *s* of the sorted union will be included in the Mash distance count, where *s* is the sketch size.
