### ISSUE TITLE
Question about "only the lexicographically smaller of the forward and reverse complement of a k-mer"

### ISSUE THREAD

**Issue by lgautier** [marbl/Mash#45]
Hi,

I have a question about the following (quote from http://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0997-x):

> For nucleotide sequence, Mash uses canonical k-mers by default to allow strand-neutral comparisons. In this case, only the lexicographically smaller of the forward and reverse complement representations of a k-mer is hashed.

Why isn't the smallest of the two hash values obtained from the forward and reverse complement representations of a k-mer selected instead ?

The selection on a lexicographic order basis amounts to a filter / sampling that I am guessing to be there to avoid having the same kmer included twice in a sketch (which might not be the most likely of events), but it would feel more natural keep the selection of on the two (forward and reverse complement) on a hash values and may allow a more natural integration of strandedness into the use of sketches.

[note: I had discussions with @ctb, @betatim, @luizirber while being unable to reproduce some of the results from sourmash - @betatim pointed me out to the lexicographic sorting-based selection I had missed]

**Comment by ctb** [comment]
Also note my rather simple "compute MinHash the mash way in pure Python"
code:

https://github.com/dib-lab/sourmash/blob/master/utils/compute-dna-mh-another-way.py

which I wrote the 3rd time I got concerned that sourmash was computing
MinHashes the wrong way :)

**Comment by aphillippy** [comment]
@lgautier I remember having this conversation with @ondovb when he was implementing it, and I suggested the same thing (using smallest hash value). I think he tested it and the lexicographical check was faster than hashing twice, so we went with that.

The idea of using canonical mers is to avoid missing reverse complement matches. You don't know in advance which strand of the DNA you are getting, so this approach makes things work in the case the reference is forward strand and the query is reverse strand. It doesn't matter how you pick the canonical mer, so long as it is deterministic. Lexicographically smallest is the usual choice.

**Comment by lgautier** [comment]
Thanks for the answer.

This is all fine in an exclusively double-stranded world, which is perfectly good in the context of the MASH paper: all genomes that double-stranded entities in the wild, and while they are represented by one of the 2 strands in the "reference genome" string it makes sense to consider a sketch cover the reverse complement to capture eventual evolutionary events that would involve strand-changing genomic rearrangements.

Effectively, selecting  based on the lexicographic order of the forward *vs* reverse complement is acting as a kind of coin-flip sampler / filter at the level of sliding windows over 2-stranded DNA. If making a symbolic (and ASCII) representation of sliding windows across a sequence, and this amounts to picking up one of the two strands for each window.

```
SQ  w w w w w w
    | | | | | |
FW  - X X X - -
RC  X - - - X X

- : hash value considered for inclusion in the sketch
X : hash value not considered
```

However, when going beyond that use-case I am thinking that it may make sense to consider the ensemble of physically occurring kmers (both strands in the case of genomic DNA) and compute the sketch (which is the selection of hash values) from that ensemble. In other words, selecting on the hash values rather than the lexicographic order this allows one to consider two strands as the source of hash values that are candidate for inclusion in the sketch, and this would allow to line up sketches for double-stranded biological entities (e.g., double-stranded genome) along with sketches for single-stranded biological entities (e.g., RNA or single-stranded virii) when looking for best matches. When considering raw sequencing data, obviously strand-specific / direct sequencing of DNA / RNA molecule is required. 

(note: in the grand scheme of things, I am not sure that the computational cost of hashing matters that much).

**Comment by aphillippy** [comment]
I don't see your distinction between defining the canonical mer on hash value vs. lexi order. If you are using any canonical mer definition, the resulting object simultaneously represents both the fwd and rev mer. It doesn't matter what you decide to "name" that object. Typically you also remember the strand from which the mer came from so you can resolve the strand agreement of any matches later on.

I do agree we could think more about how to represent strand in the sketches, e.g. if you want to enforce matching only to a specific strand in the database, but in past experience such cases crop up very rarely. The only time this has mattered for me has been probe design (pcr, microarray, etc). For everything else, viruses included, it's usually easiest to just imagine them as double stranded for the purposes of search, then use the strand origin info to work out if a match is on the correct strand or not. This saves both space and time, since instead of always storing/hashing 2 kmers, you only need to store 1 kmer + 1 strand bit.

**Comment by lgautier** [comment]
I think that I did not highlight the use-cases and rationale behind this. I'll have an other try to see if this is making sense.

I agree about the time saving (although the fraction of the total time saved would be an interesting data point) but I would not see the strand information (1 strand vs 2 strands) being required below sketch level (and it could be argued that this is optional). As you mention it, which strand a kmer/hash value is coming from can be reverse-engineered easily.

The idea would be that the sketch represents a "physical" presence, that is a sample of polymers of nucleic acids / oligos that are effectively there.

In the case of double-stranded DNA genomes, both the forward and reverse complement will "exist" (either in the abstract sense if building sketches for genome assemblies, or if building sketches for reads obtained from an NGS assay), but in the case of, for example, mRNA collections (e.g., RefSeq) or strand-specific RNA-Seq there will be only one strand.

Looking for the simplest possible example to illustrate where it  may matter I am coming up with this:

- build a sketch for a transcriptome of interest
- run a strand-specific RNA-Seq assay, and build a sketch for the data in the sequencing run
- compare the sketches (Jaccard index): index close to 1 means that the assay is about the transcriptome of interest, index around .5 may mean that the assay was not as "strand-specific" as thought / advertised.

This later point could be verified by also having a sketch for both the forward and reverse sequences in a transcriptome of interest. The Jaccard index should then be closer to one. A possible interesting point here is that sketches build from single stranded and double stranded versions can be put together in the same search structure (e.g., in a sequence bloom tree). 

For this to work it would require that FW/RC originated hash values are only considered for inclusion in the sketch based on whether they are among the n-smallest elements (without any lexicographic order-based filtering). Should the computational concern ever become a concern, this hash value rank-only method would also provide a simple a very efficient way to parallelize the code since `minhash(FW + RC) = minhash(minhash(FW) U minhash(RC))` .

**Comment by aphillippy** [comment]
Ah. I follow you better now. For your use case one could just use the single-stranded Mash option that turns off canonical mers.

As for making it more generalized by always sketching both forward and reverse ... my immediate reaction is that I still like the canonical mode better since it addresses my primary use case. E.g. when comparing two bacterial genomes (or metagenomes) I want it to be strand oblivious (so to not penalize inversions, etc). The canonical sketches give me this. In your formulation I'd always need to union the FW and RC sketches prior to computing the distance.

Any reason you could not accomplish what you want by simply keeping two single-strand sketch objects for each double-stranded sequence? That would kick this problem/decision to the index code rather than the data structure (i.e. JS spec).

**Comment by lgautier** [comment]
> Ah. I follow you better now. For your use case one could just use the single-stranded Mash option that turns off canonical mers.

But in that case, one either has the one stranded sketch, or the lexicographic order-filtered two stranded sketch.

> As for making it more generalized by always sketching both forward and reverse ... my immediate reaction is that I still like the canonical mode better since it addresses my primary use case. E.g. when comparing two bacterial genomes (or metagenomes) I want it to be strand oblivious (so to not penalize inversions, etc). 

There is a way to see it that would make the proposed alternative formulation more general.

Under that model, sketches are computed according to what they _represent_. In order words, if a two-stranded entity, such as a genome, the two stranded version is computed and if a one-stranded entity, such as RNA, the sketch is done for one strand (FW). The advantage of doing so is that if one does not now for sure whether query data is about single or double stranded entity (see example about RNA-Seq in earlier comment) it is a matter of just building the sketch for that query data and query a compendium/database of sketches/signatures that can contain sketches from single and double stranded entities.

Your use case (double-stranded genome/double-stranded genome similarities) would still work. The only difference is that hash values that make it to the sketch are selected from the set of hash values that is the union of the sets of hash values that can be created from the FW and RC.

This is coming at a computing cost that is 
```
(2 * compute-hash-values) - (compute-hash-values + compare-FWvsRC-kmers)
```
but the `2 * compute-hash-values` is trivial to parallelize (see earlier comment).

> The canonical sketches give me this. In your formulation I'd always need to union the FW and RC sketches prior to computing the distance.

Not necessarily. If your entity double stranded (e.g., a double-stranded genome) you compute the sketch once for all and store that sketch. If the perspective of computing more hash-values is a limiting factor, I am highlighting that the sketch for the union of sketches makes is trivial to parallelize the process.

> Any reason you could not accomplish what you want by simply keeping two single-strand sketch objects for each double-stranded sequence? That would kick this problem/decision to the index code rather than the data structure (i.e. JS spec).

I am not sure to follow the idea (may because I am not familiar with JS spec).

**Comment by aphillippy** [comment]
Yes, I follow you now. Thanks for clarifying; sorry for the slow response. Mash unlikely to change significantly in the near future, but will keep your arguments in mind going forward.
