### ISSUE TITLE
Recommended options for protein database?

### ISSUE THREAD

**Issue by h-2** [marbl/Mash#54]
Maybe this is totally off, but I wanted to test this with protein sequences, i.e. I sketched uniprot_sprot.fasta (with -i)  [roughly 200MB] and then a subset of uniprot_fasta [roughly 6MB] with the same options. I then called dist on them, but Mash never finishes...
I know it's not optimized for local comparisons and that the sequences are not equal length... in any case, what kind of -s and -k would you recommend?

**Comment by ondovb** [comment]
Defaults should be reasonable, assuming you had `-a` in addition to `-i`. When you say it never finishes, how long did you give it? Those are quite a few pairwise comparisons, so it could take hours. Parallelization with `-p` would help if you have the cores.
