### ISSUE TITLE
mash dist with -l: "ERROR: Did not find fasta records"

### ISSUE THREAD

**Issue by snayfach** [marbl/Mash#55]
I've encountered a possible bug in mash version 1.1.1 using the following command:
`mash dist -p 5 sketch.msh -l genome_list.txt`

where, `sketch.msh` is a sketch containing 129k genomes and `genome_list.txt` contains the path to those same genomes

That command produces the error:
`ERROR: Did not find fasta records in "/path/to/fna/1281156.3.fna".`

Which is weird because there ARE fasta records in that file. Further, this command works fine:
```
echo /path/to/fna/1281156.3.fna > genome_path.txt
mash dist -p 5 sketch.msh -l genome_path.txt
```
as does this one:
`mash dist -p 5 sketch.msh /path/to/1281156.3.fna`

I thought the issue might be related to the # of threads (`-p 5`). I tried re-running the first command without specifying the number of threads:
`mash dist sketch.msh -l genome_list.txt`

this seems to maybe be working? It was still running after about 30 minutes and didn't produce any error or output. The previous commands took only a minute or two to produce an error or output.

I've gotten around this issue for the time being by running mash dist over a loop, but a solution using a single mash command would be preferred. Any ideas?

**Comment by ondovb** [comment]
Looks like the same issue as #41. Fix is in master; release coming soon!

**Comment by ondovb** [comment]
Fixed in [v2.0](https://github.com/marbl/Mash/releases/tag/v2.0). Please reopen if issues persist.

**Comment by balags1** [comment]
This issue seems to persist in Mash v2.3, just noted.

**Comment by balags1** [comment]
Noted may be in error, my apologies, there was a file format issue.
