### ISSUE TITLE
ERROR: could not open genome1.fna for reading.

### ISSUE THREAD

**Issue by wrmrrd** [marbl/Mash#57]
Maybe it's because I'm new to linux (and I'm not fully aware of everything yet) but when I try to do sketching in the tutorial with `mash sketch genome1.fna` or distance estimation with `mash dist genome1.fna genome2.fna` I get the  error:
 `ERROR: could not open genome1.fna for reading`. 
This happens despite doing `sudo chmod -R 777 </path>` and having all permissions of files set to read and write. Is this a bug or am I doing something wrong? I'm running Mash on a Oracle VM with Biolinux-8.0.7

**Comment by ondovb** [comment]
Have you switched to the directory containing `genome1.fna` using `cd`? If not you will have to either do that or provide the full path, e.g. `/home/<user>/genome1.fna`.

**Comment by wrmrrd** [comment]
Hi Brian, thank you very much. That was indeed the problem. I didn't specify it to the subfolder (`/home/<user>/Mash-1.1.1/data`) that contained `genome1.fna`. but only to the Mash-1.1.1 folder (`/home/<user>/Mash-1.1.1`).
