### ISSUE TITLE
ERROR:reading

### ISSUE THREAD

**Issue by This12** [marbl/Mash#58]
I want to sketch my fasta file, but it have error massage by ERROR: reading filename.fasta.
Can't I use fasta file? Or orther reason?
(I use **./mash sketch -s 1000 -k 17 filename.fasta** and **./mash sketch filename.fasta**, didn't work)

**Comment by skoren** [comment]
Fasta files should be supported. You may need to provide the full path to the filename.fasta file (see issue #57). What does ls return in the directory you're running the command?

**Comment by This12** [comment]
Thank you for answer! 
But I use full path <./mash sketch /bip7_disk/shiyu106/mash-Linux64-v1.1.1/filename.fasta>, it still get ERROR: reading /bip7_disk/shiyu106/mash-Linux64-v1.1.1/filename.fasta, and _**ls**_ doesn't return me any files or orthers.
The second question is ERROR: could not open /fullpath/genomic.fna.msh for writing(when I sketch), but I can sketch orther files of this directory.
And the last question is that I want to know what's inside the RefSeqSketches.msh, is it have the all species, virus, fungi and something else?
Thank you for help.

**Comment by ondovb** [comment]
RefseqSketches.msh is built on “refseq complete”, which contains genomes of all domains and plasmids. To help with the other errors, could you paste in the exact commands along with the output of “ls”?

**Comment by This12** [comment]
Thank you for answer!
But I am not really sure what is **_ls_** ...... , is the command to view the files of directory?

**Comment by ondovb** [comment]
Exactly, just so we can see the context. A screen grab of the terminal window could also be useful if you don't mind sharing.

**Comment by This12** [comment]
![mash](https://user-images.githubusercontent.com/32285862/31162388-abf23bb6-a90f-11e7-95b5-875484415844.PNG)
![mash2](https://user-images.githubusercontent.com/32285862/31162390-afd87eca-a90f-11e7-8390-d7582d9356f2.PNG)
Sorry I'm late for reply, the first picture is first question, the second picture is second question, and both of them are not create or return any files...

**Comment by ondovb** [comment]
That looks fine. You may need to go to your system administrator for this, as I think it is likely a permissions problem or other issue beyond Mash.

**Comment by This12** [comment]
OK, I will keep trying.
Thank for your help!
