### ISSUE TITLE
Thread support for "mash sketch" ?

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#6]
I was wondering if you will be adding `--threads` to `mash sketch` to simplify the manual step of sketching in chunks then pasting together?

**Comment by ondovb** [comment]
There is some engineering to do here because of complications from the `-i` option, but this is on our wishlist.

**Comment by ondovb** [comment]
Fixed in [v1.1](https://github.com/marbl/Mash/releases/tag/v1.1).
