### ISSUE TITLE
Screen Error

### ISSUE THREAD

**Issue by GretchenWilson** [marbl/Mash#60]
Any Idea what might be causing this error with "screen"? Is it a dependency issue? The refseq sketch is the one provided in the source code files.

```
$ mash screen docs/refseq.msh SRR1188440.fastq
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  capnp/serialize.c++:43: failed: expected array.size() >= offset; Message ends prematurely in segment table.
stack: 0x4239f9 0x42a969 0x40febf 0x43505a 0x41cffb 0x404695 0x7f8200acd830 0x405759
Aborted (core dumped)
```

**Comment by GretchenWilson** [comment]
I appears to be an issue with the refseq sketch file. When I used a refseq sketch (RefSeqSketches.msh.gz or RefSeqSketchesDefaults.msh.gz)  downloaded previously from your read the docs there doesn't appear to be any issue. 

What is the intended purpose of the refseq sketch included in the source code data directory?

**Comment by ondovb** [comment]
This is an artifact from previously hosting it on GitHub and should probably be deleted. Sorry for the confusion!

Also just FYI, we recently updated the docs with a new RefSeq sketch ([refseq.genomes.k21.s1000.msh](https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh)), which is a more recent RefSeq build, is better arranged by assemblies, and has a larger sketch size, which should help `screen` results for eukaryotes. Please let us know if you try this one and have any issues with it.

**Comment by ondovb** [comment]
LFS stub for the `data/refseq.msh` file removed.

**Comment by GretchenWilson** [comment]
A little late, but thanks for your help!
