### ISSUE TITLE
How to interpret "median-multiplicity"  for screen command output? 

### ISSUE THREAD

**Issue by deepthoughts** [marbl/Mash#61]
I know the definition from the manual: "median-multiplicity is computed for shared hashes, based on the number of observations of those hashes within the pool". 
Can it be considered as a proxy for abundance along with the shared hashes?
Screen command is awesome. 
Thanks for making Mash.

**Comment by ondovb** [comment]
Hi @deepthoughts,
Glad you are finding it useful! This is actually a good question that is tricky to answer. Abundance is certainly one of the potential uses we had in mind for this value. However, we have not studied the true statistical relationship between the two. So I would say yes, as a rough estimate, but also caution that it will be affected by the other ways that Screen is not a classifier, e.g. ambiguity between genomes and conflation of identity with coverage.

**Comment by MJCarvalho** [comment]
Hi!
I am finding difficult to understand how shared hashes and median multiplicity relate? I mean how to interpret the results.
E.g shared hashes = 999/1000 and median multiplicity = 9. Does this mean the median number of time shared hashes were 999/1000 was 9? 
Thanks.
