### ISSUE TITLE
Seed mismatch error

### ISSUE THREAD

**Issue by koakeson** [marbl/Mash#62]
I am running into an error when running mash dist. Unless I use -S 0 when sketching and calculating distance I run into an error telling me the seeds do not match and the file will be skipped.

**Comment by ondovb** [comment]
Hi @koakeson,

Did you happen to download right when it was released a few weeks ago? There were these kinds of problems with the original binaries, which were replaced shortly after. If re-downloading doesn't help, can you provide an example of the sequence of commands you are using, and the origin of any pre-downloaded sketch files?

**Comment by koakeson** [comment]
Hi ondovb,

It was downloaded via linuxbrew/macbrew I will download the binaries from the main site and let you know how it goes. 

Thanks!

**Comment by koakeson** [comment]
That fixed the issue! Thank you!
