### ISSUE TITLE
mash dist sending stderr to stdout?

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#7]
When I run this command

`mash dist -p 32 ref.fa query1.fa query2.fa query3.fa`

the output is all to `stdout` and it is the sketching debug output for each contig in the query files, intermixed with the tab-sep output distance table.

Does this seem correct?

**Comment by ondovb** [comment]
If this is the "length: " lines, then it was just overlooked debug output and should be fixed now. There is other "sketching..." output that should be to stderr.
