### ISSUE TITLE
How 64 bit hash is used?

### ISSUE THREAD

**Issue by ZeweiSong** [marbl/Mash#72]
I'm just curious ...

Based on mmh3:

    >>> mmh3.hash64('foo')  # two 64-bit signed ints (the 128-bit hash sliced in half)
    (-2129773440516405919, 9128664383759220103)

How is 64 bit hash being use? Thanks!

**Comment by ondovb** [comment]
This is a function of the Python mmh3 wrapper, which is not used by Mash. We do slice a 64 or 32 bit hash (depending on k-mer size) from the 128-bit hash in a similar way though. The rest of the hash is ignored.
