### ISSUE TITLE
installation problems with Mash/capnp

### ISSUE THREAD

**Issue by yhg926** [marbl/Mash#78]
Hi, would you please help with this?: I have install capnp but configure still report porblems: 
bash-3.2$ ./configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for capnp... yes
checking capnp/common.h usability... no
checking capnp/common.h presence... yes
configure: WARNING: capnp/common.h: present but cannot be compiled
configure: WARNING: capnp/common.h:     check for missing prerequisite headers?
configure: WARNING: capnp/common.h: see the Autoconf documentation
configure: WARNING: capnp/common.h:     section "Present But Cannot Be Compiled"
configure: WARNING: capnp/common.h: proceeding with the compiler's result
checking for capnp/common.h... no
configure: error: Cap'n Proto headers not found.

**Comment by ondovb** [comment]
Looks like you were able to resolve this based on your subsequent issue?

**Comment by vinaysb** [comment]
I still have this issue, any solutions?

**Comment by alienzj** [comment]
see https://github.com/marbl/Mash/issues/98

**Comment by alienzj** [comment]
#98

**Comment by alienzj** [comment]
@yhg926 #98
