### ISSUE TITLE
mash configure error --with-gsl can not find gsl 

### ISSUE THREAD

**Issue by yhg926** [marbl/Mash#79]
Hi, could you help me with this ?
I have installed the gsl library , and feed the path to --with-gsl , but it just not work:

[yhg@jinlab2 Mash]$ ./configure --with-capnp=/usr/ --with-gsl=/home/yhg/tools/gsl-2.4
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for capnp... yes
checking capnp/common.h usability... yes
checking capnp/common.h presence... yes
checking for capnp/common.h... yes
checking gsl/gsl_cdf.h usability... no
checking gsl/gsl_cdf.h presence... no
checking for gsl/gsl_cdf.h... no
configure: error: GNU Scientific Library headers not found.
[yhg@jinlab2 Mash]$ ls -l /home/yhg/tools/gsl-2.4/gsl |head
total 36
lrwxrwxrwx. 1 yhg Jin    18 Feb 28 14:40 gsl_blas.h -> ../blas/gsl_blas.h
lrwxrwxrwx. 1 yhg Jin    24 Feb 28 14:40 gsl_blas_types.h -> ../blas/gsl_blas_types.h
lrwxrwxrwx. 1 yhg Jin    25 Feb 28 14:40 gsl_block_char.h -> ../block/gsl_block_char.h
lrwxrwxrwx. 1 yhg Jin    35 Feb 28 14:40 gsl_block_complex_double.h -> ../block/gsl_block_complex_double.h
lrwxrwxrwx. 1 yhg Jin    34 Feb 28 14:40 gsl_block_complex_float.h -> ../block/gsl_block_complex_float.h
lrwxrwxrwx. 1 yhg Jin    40 Feb 28 14:40 gsl_block_complex_long_double.h -> ../block/gsl_block_complex_long_double.h
lrwxrwxrwx. 1 yhg Jin    27 Feb 28 14:40 gsl_block_double.h -> ../block/gsl_block_double.h
lrwxrwxrwx. 1 yhg Jin    26 Feb 28 14:40 gsl_block_float.h -> ../block/gsl_block_float.h
lrwxrwxrwx. 1 yhg Jin    20 Feb 28 14:40 gsl_block.h -> ../block/gsl_block.h

**Comment by ondovb** [comment]
The —with-gsl flag needs the installation folder (rather than the source folder), which should contain an “include” folder after running GSL’s “make install”. This would probably be /usr/local by default. If it’s installed there the —with-gsl flag should not needed for mash.
