### ISSUE TITLE
Need option between mash info & mash info -H

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#8]
`mash info` spits out lines for every sequence in the mash (including bonus blank lines between each).

`mash info -H` just prints the header.

What I'd like is the concise behaviour of `mash info -H` but with the extra info of how many sketches there are in the mash, like the default `mash info` tells you eg. `Sketches (694)`

**Comment by ondovb** [comment]
Listing sketch count in `-H` makes sense. Also, the blank lines are a product of the column-formatting code. An option to skip the header and print sketches in simple tab format may make sense here.

**Comment by ondovb** [comment]
Listing sketch count in `-H` makes sense. Also, the blank lines are a product of the column-formatting code. An option to skip the header and print sketches in simple tab format may make sense here.

**Comment by ondovb** [comment]
Fixed in [v1.1](https://github.com/marbl/Mash/releases/tag/v1.1).
Also adds tabular format (`-t`) for easier parsing.
