### ISSUE TITLE
How can I sketch without writing a file?

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#84]
NOTE: THIS IS NOT REALLY THAT IMPORTANT TO FIX

I actually only want the `Estimated genome size: ` result

```
mash sketch -o /dev/null -r R1.fq.gz
Sketching R1.fq.gz...
Estimated genome size: 2.18701e+06
Estimated coverage:    2.97
Writing to /dev/null.msh...
ERROR: could not open /dev/null.msh for writing.
```
Because you force appending `.msh` I can't really do it without writing+deleting a file.

**Comment by kloetzl** [comment]
This should work:

    ln -s /dev/null blackhole.msh
    mash sketch -o blackhole -r R1.fq.gz

**Comment by tseemann** [comment]
It does indeed work - thanls @kloetzl !
