### ISSUE TITLE
Options List

### ISSUE THREAD

**Issue by micromania2** [marbl/Mash#88]
Is there an options list for MASH?

Thanks in advance.

**Comment by ondovb** [comment]
`mash [command] -h`

**Comment by micromania2** [comment]
$ mash -h

Mash version 2.0

Type 'mash --license' for license and copyright information.

Usage:

  mash <command> [options] [arguments ...]

Commands:

  bounds  Print a table of Mash error bounds.

  dist    Estimate the distance of query sequences to references.

  info    Display information about sketch files.

  paste   Create a single sketch file from multiple sketch files.

  screen  Determine whether query sequences are within a larger pool of
          sequences.

  sketch  Create sketches (reduced representations for fast operations).

**Comment by micromania2** [comment]
Unfortunately, I do not see a list of options.

**Comment by micromania2** [comment]
Never mind I got it :)\
