### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Anto007** [marbl/Mash#92]
Hi,

I would highly appreciate any help with overcoming the below error. Many thanks in advance!

~/tools/Mash-master$ make
g++ -O3 -std=c++11 -Isrc -I/usr/include -I/usr/local//include -include src/mash/memcpyLink.h -Wl,--wrap=memcpy  -o mash src/mash/memcpyWrap.o libmash.a /usr/local/lib/libcapnp.a /usr/local/lib/libkj.a -L/usr/local/lib -lgsl -lgslcblas -lstdc++ -lz -lm -lpthread
libmash.a(Sketch.o): In function `Sketch::initParametersFromCapnp(char const*)':
Sketch.cpp:(.text+0x1ae4): undefined reference to `capnp::_::PointerReader::isNull() const'
Sketch.cpp:(.text+0x1c5f): undefined reference to `capnp::_::PointerReader::isNull() const'
libmash.a(Sketch.o): In function `loadCapnp(Sketch::SketchInput*)':
Sketch.cpp:(.text+0x3e7d): undefined reference to `capnp::_::PointerReader::isNull() const'
Sketch.cpp:(.text+0x4372): undefined reference to `capnp::_::PointerReader::isNull() const'
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'mash' failed
make: *** [mash] Error 1

**Comment by ondovb** [comment]
Hi @Anto007,

What is your OS and your Capnp version?

**Comment by Anto007** [comment]
Thanks for your response. My Cap'n Proto version is 0.6.1 and my OS is Ubuntu 16.04

**Comment by ondovb** [comment]
I was not able to reproduce this. Could you try a `make clean` and then `configure` and `make` again from scratch? I would also make sure that the `capnp` install completed without errors.

**Comment by Anto007** [comment]
I did make clean and ran all the steps from scratch and it worked for me. Many thanks-much appreciated!
