### ISSUE TITLE
ERROR: The option p cannot be used with r.

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#99]
`ERROR: The option p cannot be used with r.`

This change in v2.1 has broken 4 of my pipelines.
Compatibility doesn't normally break on a `x.1` release.
Just FYI that this might make people confused and/or angry :)   (i'm ok)

**Comment by tseemann** [comment]
This is breaking lots of other tools now eg. mashtree.

**Comment by ondovb** [comment]
I can weaken this from an error to a warning, but sketching with `-r` doesn't use threads and never has, and pipelines should updated to reflect this (see #86).

**Comment by ondovb** [comment]
Reduced to warning in 2.1.1.
